### ISSUE TITLE
Seemingly incompatible with wildcard.foldercontents 2.0b3 

### ISSUE THREAD

**Issue by dgroos** [collective/collective.lineage#26]
While foldercontents works at the site root (see image 1) it does not work in any part of a child site (such as image 2)

Image 1, Site Root
![ss_539](https://cloud.githubusercontent.com/assets/4097759/4434979/2148c344-472f-11e4-929f-48a6e660029b.png)

Image 2, Child Site
![ss_538](https://cloud.githubusercontent.com/assets/4097759/4434980/2a32c63a-472f-11e4-925c-81777f515f08.png)

**Comment by rnunez80** [comment]
I have the same behavior issue in 4.3 with plone.app.toolbar as well as plone5, definitely need to be fix if you are going to call the lineage 2.0 compatible with plone5

**Comment by thet** [comment]
fixed via https://github.com/plone/plone.app.widgets/pull/101/files
only, this has to be forward-ported to plone 5, as this pull-request targets plone.app.widgets 1.x.

**Comment by thet** [comment]
the mentioned pull request https://github.com/plone/plone.app.widgets/pull/101 got it's way into plone.app.content. see: https://github.com/plone/plone.app.content/blob/master/plone/app/content/browser/vocabulary.py

this bug is also related to this fix: https://github.com/collective/wildcard.foldercontents/commit/aeafd48bc4ac44a3c294ef4d07fbb639719b444d
