### ISSUE TITLE
Question about releases

### ISSUE THREAD

**Issue by fulv** [collective/collective.lineage#46]
I see that version 1.1.3 was released on 2016-04-16, while the only thing I can find about a 2.x series is https://pypi.python.org/pypi/collective.lineage/2.0, which says it was uploaded on 2014-10-29.  There are no tags or releases in github for the 2.x series, so it's hard to know what commits went into it.  However, I like that there is no dependency on p4a.subtyper, according to the readme.

Given this, what is the status and plans for 2.x?
I installed 2.0 on a 4.3.9 site, not realizing that it was a dead end (if indeed it is).  Should I downgrade to 1.1.3?

Background:  I'm struggling to find the best solution to #26, given that I have collective.lineage 2.0 and wildcard.foldercontents 2.0b4 (another dead end?).

**Comment by thet** [comment]
The 2.x series / master branch is definitely the way to go! The latest 1.1.x series is only for having an easier upgrade story for the 2.x branch. I'm using the 2.x series since I made the changes which lead to this version change. Not having a dependency on p4a.subtyper is a very good thing.
Releases of lineage are made quite irregular. Also, it was forgotten to make release-tags.
See: https://github.com/collective/collective.lineage/issues/39

**Comment by fulv** [comment]
Thanks, @thet!
